name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: List files to check structure
        run: ls -R
